export interface iData {
  name: string;
  yahooSymbol: string;
  ticker: string;
  currency: string;
  newsParam: string;
}

export const data: iData[] = [
  {
    ticker: "ZLAB.O",
    currency: "USD",
    yahooSymbol: "ZLAB",
    name: "再鼎医药（ZLAB.US）",
    newsParam: "ZLAB",
  },
  {
    ticker: "PDD.O",
    currency: "USD",
    yahooSymbol: "PDD",
    name: "拼多多（PDD.US）",
    newsParam: "PDD",
  },
  {
    ticker: "SVA.O",
    currency: "USD",
    yahooSymbol: "SVA",
    name: "科兴生物（SVA.US）",
    newsParam: "SVA",
  },
  {
    ticker: "2142.HK",
    currency: "HKD",
    yahooSymbol: "2142.HK",
    name: "和铂医药（2142.HK）",
    newsParam: "02142",
  },
  {
    ticker: "HK9966",
    currency: "HKD",
    yahooSymbol: "9966.HK",
    name: "康宁杰瑞（9966.HK）",
    newsParam: "09966",
  },
  {
    ticker: "1875.HK",
    currency: "HKD",
    yahooSymbol: "1875.HK",
    name: "东曜药业（1875.HK）",
    newsParam: "01875",
  },
  {
    ticker: "688382.SH",
    currency: "RMB",
    yahooSymbol: "688382.SS",
    name: "益方生物（688382.SH）",
    newsParam: "688382",
  },
  {
    ticker: "CNTB.O",
    currency: "USD",
    yahooSymbol: "CNTB",
    name: "康乃德（CNTB.US）",
    newsParam: "CNTB",
  },
  {
    ticker: "ZH.N",
    currency: "USD",
    yahooSymbol: "ZH",
    name: "知乎（ZH.US）",
    newsParam: "ZH",
  },
  {
    ticker: "1244.HK",
    currency: "HKD",
    yahooSymbol: "1244.HK",
    name: "3D MEDICINES（思路迪）",
    newsParam: "01244",
  },
  {
    ticker: "6955.HK",
    currency: "HKD",
    yahooSymbol: "6955.HK",
    name: "博安生物（6955.HK）",
    newsParam: "06955",
  },
  {
    ticker: "YMM.N",
    currency: "USD",
    yahooSymbol: "YMM",
    name: "满帮（YMM.US）",
    newsParam: "YMM",
  },
  {
    ticker: "301216.SZ",
    currency: "RMB",
    yahooSymbol: "301216.SZ",
    name: "万凯新材（301216.SZ）",
    newsParam: "301216",
  },
  {
    ticker: "9886.HK",
    currency: "HKD",
    yahooSymbol: "9886.HK",
    name: "叮当健康（9886.HK）",
    newsParam: "09886",
  },
  {
    ticker: "2888.HK",
    currency: "HKD",
    yahooSymbol: "2888.HK",
    name: "Standard Chartered Bank（2888.HK）",
    newsParam: "02888",
  },
  {
    ticker: "0005.HK",
    currency: "HKD",
    yahooSymbol: "0005.HK",
    name: "HSBC（0005.HK）",
    newsParam: "00005",
  },
  {
    ticker: "3968.HK",
    currency: "HKD",
    yahooSymbol: "3968.HK",
    name: "CMB（3968.HK）",
    newsParam: "03968",
  },
  {
    ticker: "HK05",
    currency: "SGD",
    yahooSymbol: "D05.SI",
    name: "DBS（D05.SG）",
    newsParam: "",
  },
  {
    ticker: "EWBC",
    currency: "USD",
    yahooSymbol: "EWBC",
    name: "East West Bank（EWBC）",
    newsParam: "EWBC",
  },
  {
    ticker: "JPM",
    currency: "USD",
    yahooSymbol: "JPM",
    name: "JP Morgan（JPM）",
    newsParam: "JPM",
  },
  {
    ticker: "MS",
    currency: "USD",
    yahooSymbol: "MS",
    name: "Morgan Stanley（MS）",
    newsParam: "MS",
  },
  {
    ticker: "GS",
    currency: "USD",
    yahooSymbol: "GS",
    name: "Goldman Sachs（GS）",
    newsParam: "GS",
  },
  {
    ticker: "FCNCA",
    currency: "USD",
    yahooSymbol: "FCNCA",
    name: "First Citizens（FCNCA）",
    newsParam: "FCNCA",
  },
  {
    ticker: "UBS",
    currency: "USD",
    yahooSymbol: "UBS",
    name: "UBS（UBS）",
    newsParam: "UBS",
  },
  {
    ticker: "C",
    currency: "USD",
    yahooSymbol: "C",
    name: "Citibank（C）",
    newsParam: "C",
  },
  {
    ticker: "2590.HK",
    currency: "HKD",
    yahooSymbol: "2590.HK",
    name: "极智嘉（2590.HK）",
    newsParam: "02590",
  },
  {
    ticker: "1511.HK",
    currency: "HKD",
    yahooSymbol: "1511.HK",
    name: "驭势科技（1511.HK）",
    newsParam: "01511",
  },
  {
    ticker: "TME",
    currency: "USD",
    yahooSymbol: "TME",
    name: "TME.US",
    newsParam: "TME",
  },
  {
    ticker: "3952.HK",
    currency: "HKD",
    yahooSymbol: "3952.HK",
    name: "来福谐波（3952.HK）",
    newsParam: "03952",
  },
  {
    ticker: "6880.HK",
    currency: "HKD",
    yahooSymbol: "6880.HK",
    name: "MOMENTA-W（6880.HK）",
    newsParam: "06880",
  },
];
